# Configuration file for HeavySpleef

default-game-properties:
  instant-break: true
  play-block-break: true
  join-on-countdown: true
  disable-hunger: true
  disable-pvp: true
  disable-damage: true
  disable-item-pickup: true
  disable-item-drop: true
  disable-build: true
  use-liquid-deathzone: true
  disable-floor-break: false
  broadcast-radius: 30
  
localization:
  locale: en