####################################
### -- HeavySpleef  -  Config -- ###
### Developed by matzefratze123  ###
####################################
#
# This is the main configuration file of HeavySpleef.
#
# If the server stopps correctly and a game is running
# the game will be stopped and players that joins the
# next time will be automatically teleported out of the
# game. Use '/spleef save' to save all data of the spleef
# games to the database...

# Should the plugin automatically download the new version of
# HeavySpleef.jar if there is an update avaible?
# You'll find updates in the folder /plugins/Up 
auto-update: true

general:
  
  # Should spleef messages be globally broadcasted? If false the messages will be
  # broadcasted if a player has a specified radius from the arena (Configurable)
  # If true, the messages will be broadcasted for every player... 
  globalBroadcast: false
  
  # How far away should spleefmessages be broadcasted for players?
  # This works only if the globalBroadcast is set to false...
  broadcast-radius: 40
  
  # Which spleef prefix should be used?
  spleef-prefix: '&c[&6Spleef&c]'
  
  # Should player inventorys and other stuff (for expample health, foodlevel etc.) be cleared and saved?
  # The state of the player will be restored on leave, lose and win.
  savePlayerState: true
  
  # Should an arena be protected?
  protectArena: true
  
  # Set the length of the default countdown until a game is starting
  countdownFrom: 10
  
  # Default value of players that have to be in the lobby to start a game...
  neededPlayers: 2
  
  # Should games be saved to the database at intervall time?
  # This can cause lag but it's saver if you set this to true...
  # (You can save games manually with the command: /spleef save)
  saveInIntervall: false
  
  # In which intervall should games be saved?
  # (Only works if saveInIntervall is set to true)
  # (In minutes)
  saveIntervall: 30
  
  # Default value that the players must pay to play a game.
  # Only works if Vault is enabled!
  # (money value can be configured for every game)
  defaultToPay: 5
  
  # Default reward value for the winner
  # Only works if Vault is enabled!
  # (reward value can be configured for every game)
  defaultReward: 0
  
  # Should the build in HeavySpleef selection system be used
  # or the WorldEdit wand selection? (allowed values: WorldEdit, HeavySpleef)
  wandType: 'HeavySpleef'
  
  # Which wand tool should be used?
  # (Default: 280 = Stick)
  # Only works if wandType is set to 'HeavySpleef'
  wandItem: 280
  
  # Command Whitelist
  # A list of commands that users can use while spleefing...
  commandWhitelist:
  - /spleef
  - /money
  - /msg
  - /tell
  
  # Should players be able to join the game while it's counting?
  joinAtCountdown: true
  
  # Language that should be used (Accepted: en, de, ru | fr isn't supported yet...)
  language: en
  
  # Should there be a countdown between a round of a 1vs1 game?
  countdownBetweenRound: true
  
  # How long should the countdown between a round be?
  # Only works if countdownBetweenRounds is set to true!
  countdownBetweenRoundLength: 5
  
anticamping:

  # Should the anti-camping feature be enabled?
  # If true, players can't camp in corners to win
  # the game! They will be teleported a floor down if they camp...
  enabled: true

  # Should a player be warned of camping?
  campWarn: true

  # At how many seconds of camping should a warning be send to the player?
  # (Only works if campWarn is set to true)
  warnAt: 3
  
  # At how many seconds of camping should a player teleported one floor down?
  teleportAt: 6
  
sounds:

  # Should a pling sound be played if a player joins a game? This sound
  # will be only heared by players that joined the game...
  plingSound: true
  
  # Should a levelup sound be played to the player that wins the game?
  levelUp: true
  
blocks:

  # A list of blocks that can't be broken by players while spleefing (only id is permitted)
  cantBreak:
  - 20 # Glass
  - 89 # Glowstone
  - 49 # Obsidian
  
  # Should water and lava be an automatic losezone?
  loseOnTouchWaterOrLava: true
  
statistic:

  # Which database type should be used for statistic database storing?
  # Allowed types: 'yaml', 'mysql'
  dbType: yaml
  
  # If you use mysql you have to fill the following things:
  
  host: 'localhost'
  port: '3306'
  databaseName: ''
  user: 'root'
  password: ''
  
# How much... No, you've finished the configuration ;)