####################################
### -- HeavySpleef  -  Config -- ###
### Developed by matzefratze123  ###
####################################
#
# This is the main configuration file of HeavySpleef.
#
# If the server stopps correctly and a game is running
# the game will be stopped and players that joins the
# next time will be automatically teleported out of the
# game. Use '/spleef save' to save all data of the spleef
# games to the database...

# Should the plugin  download the new version of
# HeavySpleef.jar if there is an update avaible? (/spleef update)
# You'll find updates in the folder /plugins/update
# The plugin will be auto installed by bukkit at the next
# server reload / restart...
auto-update: true

general:
  
  # Should spleef messages be globally broadcasted? If false the messages will be
  # broadcasted if a player has a specified radius from the arena (Configurable)
  # If true, the messages will be broadcasted for every player... 
  globalBroadcast: false
  
  # How far away should spleefmessages be broadcasted for players?
  # This works only if the globalBroadcast is set to false...
  broadcast-radius: 40
  
  # Which spleef prefix should be used?
  spleef-prefix: '&c[&6Spleef&c]'
  
  # Should player inventorys and other stuff (for expample health, foodlevel etc.) be cleared and saved?
  # The state of the player will be restored on leave, lose and win.
  savePlayerState: true
  
  # Should arenas be protected?
  protectArena: true
  
  # Should games be saved to the database at intervall time?
  # This can cause lag but it's saver if you set this to true...
  # (You can save games manually with the command: /spleef save)
  saveInIntervall: false
  
  # In which intervall should games be saved?
  # (Only works if saveInIntervall is set to true)
  # (In minutes)
  saveIntervall: 30
  
  # Should the built-in HeavySpleef selection system be used
  # or the WorldEdit wand selection? (allowed values: WorldEdit, HeavySpleef)
  wandType: 'HeavySpleef'
  
  # Which wand tool should be used?
  # (Default: 280 = Stick)
  # Only works if wandType is set to 'HeavySpleef'
  wandItem: 280
  
  # Command Whitelist
  # A list of commands that users can use while spleefing...
  commandWhitelist:
  - /spleef
  - /money
  - /msg
  - /tell
  
  # Should players be able to join the game while it's counting?
  joinAtCountdown: true
  
  # Should there be a countdown between a round of a 1vs1 game?
  countdownBetweenRound: true
  
  # How long should the countdown between a round be?
  # Only works if countdownBetweenRounds is set to true!
  countdownBetweenRoundLength: 5
  
  # Should the autostart-vote feature be enabled?
  autostart-vote-enabled: true
  
  # Set how many procent of votes must be received
  # to start the game. This means that x percent of
  # players need to do /spleef vote or /spleef ready
  # to autostart the game (Only if you don't want to
  # use /spleef start)
  autostart-vote: 70
  
  # A list of vips on your server
  # Vip's will have a dark red name
  # in spleef broadcasts
  vip:
  - someone
  - anotherone
  
  # PVP Timer:
  # Some servers don't want that players can instantly
  # teleport to a spleef game to escape from a battle.
  # Here you can configure an amount of x seconds they have
  # to wait until they can join a spleef game. 
  # Set this to 0 to disable this function
  pvptimer: 0
  
  # The plugin can show ingame players a sidebar scoreboard
  # with the knockouts and the status. To use this, you have
  # to install the latest 1.5.1 R2 build of bukkit.
  showSidebarScoreboard: false
  
  # This is the ready block for players who don't want to use
  # /spleef ready or /spleef vote
  # (Hit the block)
  ready-block: IRON_BLOCK
  
leaderboard:
  # Points for Spleef Games
  win: 30
  lose: -4
  knockout: 3
  gamePlayed: 3
  
flag-defaults:
  # A list of all default values for flags...
  # Please note that these values are the DEFAULT
  # values. This means that this values will only be 
  # used if there is no specified game flag!
  # Set specified game flags with /spleef flag <arena> <flag> <value>
  
  minplayers: 2
  maxplayers: 0
  autostart: 0
  countdown: 10
  jackpotamount: 0
  reward: 0
  chances: 0
  timeout: 0
  rounds: 3
  
  1vs1: false
  shovels: false
  team: false
  
  # Syntax of an itemreward flag: 'ID AMOUNT ID2 AMOUNT2 ID3 AMOUNT3 etc.'
  # Example: '264 5 388 3'. This would give 5 Diamonds and 3 Emeralds
  itemreward: ''
  losereward: ''
  
  difficulty: MEDIUM

queues:
  
  # Should queues be enabled?
  useQueues: true
  
  # Should users be allowed to use commands while in queue?
  # If you don't want that players join a spleef queue and
  # another minigame queue set this to false (You can set
  # a queues lobby with /spleef setqueuelobby <name>)
  commandsInQueue: false

scoreboards:
  # Which id should numbers of scoreboards have?
  # Please use ''
  numberID: '35:14' # Red wool
  
  # Which id should the other blocks of the scoreboard have?
  # Please use ''
  otherID: '35:15' # Black wool

language:

  # Language that should be used
  # Preinstalled languages: en, de, ru
  # Feel free to translate an own language file
  # and contact me via a PM on dev.bukkit.org to add it
  # if you want to :)
  language: en
  
  # Should messages be editable?
  # If you set this to true, you
  # find language files in the folder
  # /plugins/HeavySpleef/language
  editable: false 

anticamping:

  # Should the anti-camping feature be enabled?
  # If true, players can't camp in corners to win
  # the game! They will be teleported a floor down if they camp...
  enabled: true

  # Should a player be warned of camping?
  campWarn: true

  # At how many seconds of camping should a warning be send to the player?
  # (Only works if campWarn is set to true)
  warnAt: 3
  
  # At how many seconds of camping should a player teleported one floor down?
  teleportAt: 6
  
sounds:

  # Should a pling sound be played if a player joins a game? This sound
  # will be only heared by players that joined the game...
  plingSound: true
  
  # Should a levelup sound be played to the player that wins the game?
  levelUp: true
  
blocks:
  
  # Should water and lava be an automatic losezone?
  loseOnTouchWaterOrLava: true
  
statistic:

  # Which database type should be used for statistic database storing?
  # Allowed types: 'yaml', 'mysql'
  dbType: yaml
  
  # If you use mysql you have to fill the following things:
  
  host: 'localhost'
  port: '3306'
  databaseName: ''
  user: 'root'
  password: ''
  
# How much... No, you've finished the configuration ;)