name: HeavySpleef
description: Easy to use spleef plugin for bukkit

version: 1.0
author: matzefratze123

softdepend: [Vault, WorldEdit]
website: http://dev.bukkit.org/server-mods/heavyspleef/

main: me.matzefratze123.heavyspleef.HeavySpleef

commands:
  spleef:
    aliases: [hs, hspleef]
    description: General Spleef command for HeavySpleef