name: HeavySpleef
description: Powerful spleef plugin for Bukkit

version: DEV 0.5
author: matzefratze123

softdepend: [Vault]
website: http://dev.bukkit.org/server-mods/heavyspleef/

main: me.matzefratze123.heavyspleef.HeavySpleef

commands:
  spleef:
    aliases: [hs, hspleef]
    description: General Spleef command for HeavySpleef